### ISSUE TITLE
Landing

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#1]
The landing will include:

- [x]  A full page template with a Mailchimp widget.
- [ ]  English/Spanish support.
- [ ] install() and uninstall hooks so the former sets the page as the front page, while the latter unsets it.

**Comment by juampynr** [comment]
Next in the line is to set English & Spanish support.

**Comment by juampynr** [comment]
@nuez made a first step on this at https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/10

**Comment by juampynr** [comment]
Merged https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/11, although I haven't tested it in my local (oopsie!).

**Comment by juampynr** [comment]
@nuez, I have installed the site locally after merging your last PR and looks like this:

![image](https://cloud.githubusercontent.com/assets/108130/17962683/3cdb4ac0-6ab2-11e6-8472-7157d0295b9f.png)

@nuez, can you update the README with the installation steps? Maybe I missed something.

**Comment by nuez** [comment]
I think I forgot to update readme:

You need to run composer install in the different themes too, to install the github dependencies of javascript libraries. (I've decided to not include those javascripts in the project, for best practice)

But currently it doesn't seem to be possible to automatically run composer dependencies that present in subfolders when running composer from the project root. I've had a chat about that with leandro, haven't come across a solution yet.

**Comment by juampynr** [comment]
Since we have the landing working at http://2017.drupalcamp.es, let's close this. We will deal with multilingual and install/uninstall later.
