### ISSUE TITLE
Featured speaker adjustments

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#100]
![image](https://cloud.githubusercontent.com/assets/108130/23890701/2fdd1e1e-0893-11e7-82f2-9e31d65e6323.png)

1. Fix why bios are not being set by the db update.
2. Add Twitter logo.
3. Remove SEE ALL.
4. Adjust headshots so there aren't gray areas.

**Comment by nuez** [comment]
4. photos will have to be adjusted by @wildwildweb

**Comment by wildwildweb** [comment]
Please send me the photos or link to folder or whatever to adjust them.

**Comment by juampynr** [comment]
https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAdIAAAAJDMxMjUzOWMxLTQ5NDUtNGI2Ni1iNzczLWUzNGJmMWYyZjYwOA.jpg

https://assets.lullabot.com/styles/dynamic_resize/w640/bios/headshots-comp_0004_sally.jpg.jpg

https://assets.lullabot.com/styles/dynamic_resize/w640/bio_image/headshot-mherchel.jpg

**Comment by juampynr** [comment]
cc @wildwildweb ^^^^^^^

**Comment by juampynr** [comment]
https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/106 fixes everything except the headshots. Once we get them from @wildwildweb we will update them.
