### ISSUE TITLE
Sponsors adjustments

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#102]
First, we need to add a database update that deletes dummy sponsors and creates Sb IT as silver and Autentia as - ask @samuelsolis -

![image](https://cloud.githubusercontent.com/assets/108130/23890830/d92db73a-0893-11e7-9c09-d7562243ae8a.png)

The view is configured to show sponsors per type. It should look like

Silver:

Sb it logo goes here

Collaborators (assuming that Autentia is one)

Autentia logo goes here.

Then, we need to place the Become a Sponsor block right below the view of sponsors:
![image](https://cloud.githubusercontent.com/assets/108130/23890854/ecf1c9fa-0893-11e7-9cfc-050c1bc12663.png)

**Comment by nuez** [comment]
Wouldnt it be easier to just login and delete / create sponsors?

**Comment by samuelsolis** [comment]
@nuez is right, It seems easier.

Anyway we needs the sponsor info. Currently we only have tow confirmed sponsors as @juampynr say, Autentia and sbit.

Logos are in Drive, here: https://drive.google.com/drive/folders/0B4I4L5c7_t4zNmdaaFRITDcwNG8

**Comment by juampynr** [comment]
@nuez let's make it so we don't need to do a single thing after deployment. It will save us a lot of headaches.

**Comment by juampynr** [comment]
We have:
  - Autentia (platinum)
  - SbIt (silver)
  - OpenExpo and AED as collaborators.

**Comment by nuez** [comment]
Since this is not really programming but configuration I will leave this task to someone else.

**Comment by juampynr** [comment]
https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/105
