### ISSUE TITLE
Newsletter and footer adjustments

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#103]
![image](https://cloud.githubusercontent.com/assets/108130/23890980/7040284c-0894-11e7-9e7b-bd953ac1f6b1.png)

Looks like there is some missing theming here.

**Comment by nuez** [comment]
That's just your local...

**Comment by juampynr** [comment]
@nuez what may I be doing wrong in my local?

**Comment by nuez** [comment]
The problem is that on local you don't have a valid mailchimp configuration, so the actual input doesn't show, breaking the design a little bit. You can create a test account on mailchimp with the same list and adjust settings in settings.php.

My settings.php look like this:

````
$config['mailchimp.settings']['api_key'] = '5e571810XXXXXXeee6e366c3829-us2';
$config['mailchimp_signup.mailchimp_signup.dcamp_mailchimp']['mc_lists'] = [
  'd2ac87ce62' => 'd2ac87ce62',
];
````

**Comment by juampynr** [comment]
Gotcha, thanks.
