### ISSUE TITLE
Create a code of conduct page and link it

### ISSUE THREAD

**Issue by samuelsolis** [AsociacionDrupalES/DrupalCampSpain#109]
We have to create a code of conduct (we can copy it from drupalcon or drupaldevdays) and linked it in the footer (or where ever).

**Comment by juampynr** [comment]
@samuelsolis @isholgueras do we have anything from past years to use?

**Comment by samuelsolis** [comment]
Drupal devdays coc:
https://seville2017.drupaldays.org/code-of-conduct

Drupalcon coc:
https://www.drupal.org/dcoc

Both seems to be valid.

**Comment by samuelsolis** [comment]
Done!

https://2017.drupalcamp.es/es/codigo-de-conducta
https://2017.drupalcamp.es/code-conduct
