### ISSUE TITLE
Theme the survival guide as a full page

### ISSUE THREAD

**Issue by samuelsolis** [AsociacionDrupalES/DrupalCampSpain#110]
Now seems to have a imaginary left sidebar.

**Comment by nuez** [comment]
That was based on the designs by @wildwildweb. Maybe @wildwildweb can propose a specific design for pages.

**Comment by wildwildweb** [comment]
Guys, please check invision prototype. Node title must appear on this left sidebar. 
Every node in the page have left sidebar, and title (and sometimes more fields like in speaker detail) must appear there.

It's easy, same layout (2 columns) for every node, just some fields can change like in speaker node.

Thanks very much!!

**Comment by isholgueras** [comment]
It's already in the PR150.

**Comment by juampynr** [comment]
https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/150 Needs some adjustments.

**Comment by juampynr** [comment]
Remainder, @isholgueras

**Comment by juampynr** [comment]
https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/205
