### ISSUE TITLE
Fix button theming

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#115]
We have lost the styling of the homepage buttons:

![image](https://cloud.githubusercontent.com/assets/108130/24070421/7c24af6c-0bbd-11e7-9297-8720477dfad4.png)

![image](https://cloud.githubusercontent.com/assets/108130/24070422/815aa16c-0bbd-11e7-8164-063cc8422ddc.png)

**Comment by nuez** [comment]
Do the buttons have the .Button class?

**Comment by nuez** [comment]
This is already fixed by adding the .button class to the block. If you can give me access to the website I can fix it.

**Comment by nuez** [comment]
@juampynr

**Comment by nuez** [comment]
I think I already have a user, but it's blocked...

**Comment by juampynr** [comment]
Reactivated.

**Comment by nuez** [comment]
this fixed directly on the website
