### ISSUE TITLE
Confirmed Speakers block - Change Twitter URL for username

### ISSUE THREAD

**Issue by wildwildweb** [AsociacionDrupalES/DrupalCampSpain#123]
In confirmed Speaker block, after title, Twitter URL should be replace for twitter username.
if you dont have this field avaliable you can just cut the url and add @.
Please maintain the link to current twitter url.
Thanks very much guys!!!
![captura de pantalla 2017-03-20 a las 16 24 43](https://cloud.githubusercontent.com/assets/592608/24092797/87eaabba-0d8b-11e7-8610-91d3f82980e3.png)

**Comment by nuez** [comment]
This is build as well, just need to fill in the right fields. I've fixed this.
