### ISSUE TITLE
Confirmed Speakers block - Add company name

### ISSUE THREAD

**Issue by wildwildweb** [AsociacionDrupalES/DrupalCampSpain#124]
We miss company name between speaker name and twitter username.
![captura de pantalla 2017-03-20 a las 16 24 43](https://cloud.githubusercontent.com/assets/592608/24092824/bc15be52-0d8b-11e7-9993-e7b75596c4d5.png)

**Comment by nuez** [comment]
@juampynr @samuelsolis This is build already, just need to add the right company names and links.
