### ISSUE TITLE
Weird white gap on right side

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#127]
At https://2017.drupalcamp.es/speakers/sally-young.

![selection_005](https://cloud.githubusercontent.com/assets/108130/24136670/29c52814-0e10-11e7-9af0-06000121b369.jpg)

Happens if you are anonymous too.

**Comment by nuez** [comment]
This is solved with the replacement of the speaker image. thanks @juampynr
