### ISSUE TITLE
Texts and little bugs

### ISSUE THREAD

**Issue by AntonioGarRod** [AsociacionDrupalES/DrupalCampSpain#129]
- Add `target=_blank` on external links to open this on a new window.

- Some links on spanish version switch to english version

**Comment by juampynr** [comment]
Can you point to the specific places where this needs to be fixed?

**Comment by AntonioGarRod** [comment]
It's fixed now. It was happening at spanish homepage but I just checked again and I think that it's working fine now. The only link that seems wrong is the contact link at "Business day" block, but I think that it's a content link, It's not a interface problem. I attach a block image anyway. 

![screenshot from 2017-03-22 11-35-54](https://cloud.githubusercontent.com/assets/3091045/24193901/2d273314-0ef4-11e7-871e-f4a619034335.png)

**Comment by juampynr** [comment]
Fixed.
