### ISSUE TITLE
Expose content for the mobile App

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#133]
So far we can expose:

* Featured speakers.
* Pages.
* Sponsors.

We could additionally provide details to @ccamposfuentes on how to fetch session proposals from google forms (which is what we are using) and how to subscribe to the newsletter. However, I think that with the three items above we should have enough to start with, right @ccamposfuentes?

**Comment by ccamposfuentes** [comment]
Ok, I'ts good.

We could deploy a release with that data and update when we will have a schedule.

**Comment by juampynr** [comment]
@ccamposfuentes have a look at https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/155. This is already working at https://dev.drupalcamp.es and will be published to Production tomorrow.
