### ISSUE TITLE
Typekit error makes ugly fonts out of Production

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#141]
![image](https://cloud.githubusercontent.com/assets/108130/24548580/2fb9fbec-1616-11e7-94d2-9239326aba28.png)

cc @nuez @wildwildweb @ckrina 

What can we do?

**Comment by wildwildweb** [comment]
I added subdomain to Typekit config so now must work.

**Comment by isholgueras** [comment]
@wildwildweb, for the local environment, can we add "dc2017.local" as a trusted environment?

**Comment by wildwildweb** [comment]
@isholgueras Added!

**Comment by isholgueras** [comment]
Works fine. Thanks very much!

**Comment by juampynr** [comment]
@wildwildweb, what are the supported domains? Can we use a wildcard such as *.drupalcamp.es? Then, we could use local.drupalcamp.es locally, while dev.drupal.camp.es and www.drupalcamp.es would match the wildcard.

**Comment by wildwildweb** [comment]
@juampynr was already like that:

`localhost,127.0.0.1,wildwilddev.com.es,2017.drupalcamp.es,*.drupalcamp.es,dev.drupalcamp.es,dc2017.local`

I don't know why it's not working.

Anyway i added more domains and now it's like that:

`localhost,127.0.0.1,wildwilddev.com.es,2017.drupalcamp.es,*.drupalcamp.es,dev.drupalcamp.es,dc2017.local,local.drupalcamp.es,www.drupalcamp.es`

Please, let me know if still not working for you.
Best!

**Comment by juampynr** [comment]
Fixed.
