### ISSUE TITLE
Custom meta tag "theme-color"

### ISSUE THREAD

**Issue by wildwildweb** [AsociacionDrupalES/DrupalCampSpain#143]
Make meta tag "theme-color" works with these color: #452AE2

More info: https://developers.google.com/web/fundamentals/design-and-ui/browser-customization/

<img width="887" alt="captura de pantalla 2017-04-02 a las 12 35 37" src="https://cloud.githubusercontent.com/assets/592608/24584474/d717cf4a-17a1-11e7-835d-5b04a7acb21f.png">

**Comment by nuez** [comment]
see #221

**Comment by juampynr** [comment]
https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/221
