### ISSUE TITLE
Create Not found and Access denied pages

### ISSUE THREAD

**Issue by wildwildweb** [AsociacionDrupalES/DrupalCampSpain#144]
Create "404 - Not found" and "403 - Access denied" pages and configure Drupal to redirect to them in given case. 

<img width="1120" alt="captura de pantalla 2017-04-02 a las 12 37 03" src="https://cloud.githubusercontent.com/assets/592608/24584485/2756a3aa-17a2-11e7-9d9e-375a7e53d54c.png">
<img width="1186" alt="captura de pantalla 2017-04-02 a las 12 37 17" src="https://cloud.githubusercontent.com/assets/592608/24584486/2888cf1e-17a2-11e7-90d9-b47162d79230.png">

**Comment by juampynr** [comment]
@ckrina, @nuez: do you have any suggestions?

**Comment by nuez** [comment]
I don't know if there are designs for this, but I think the easies and most adecuate would be to just print the letters nice and big and in the middle.

Some body classes are required. This will be part of my next PR.
