### ISSUE TITLE
Adjust hamburger menu

### ISSUE THREAD

**Issue by wildwildweb** [AsociacionDrupalES/DrupalCampSpain#145]
Please adjust hamburguer menu to fit perfect. Now looks a little bit small and not centered. See attached screenshots. 
<img width="304" alt="captura de pantalla 2017-04-02 a las 12 50 03" src="https://cloud.githubusercontent.com/assets/592608/24584514/f39f1816-17a2-11e7-80d6-267b4293fe04.png">
<img width="493" alt="captura de pantalla 2017-04-02 a las 12 48 31" src="https://cloud.githubusercontent.com/assets/592608/24584515/f438dc08-17a2-11e7-9bcb-2602d215210d.png">

**Comment by isholgueras** [comment]
Fixed in PR150

**Comment by ckrina** [comment]
This one is fixed by #146.
