### ISSUE TITLE
Create hamburger menu navigation

### ISSUE THREAD

**Issue by wildwildweb** [AsociacionDrupalES/DrupalCampSpain#146]
Please, create this animation for the hamburguer menu.

https://codyhouse.co/gem/full-screen-pushing-navigation/

We dont need to include the circle around menu. Just the animation to transform the three lines into the arrow.

Thanks very much and sorry for this but i just try to do my best. Details are the key for a killer website.

**Comment by juampynr** [comment]
:hamburger: merged for a :finnadie: website https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/196
