### ISSUE TITLE
Hide background letters on small resolutions in frontpage above the fold

### ISSUE THREAD

**Issue by wildwildweb** [AsociacionDrupalES/DrupalCampSpain#148]
We can just show 1 letter in mobiles, 2 o 3 in tablets and all (5) in Desktop.
Now it's a mess in mobile and tablets showing the 5 letters.
![screenshot_20170402-123814](https://cloud.githubusercontent.com/assets/592608/24584573/561941dc-17a4-11e7-84ce-f041cff5100b.png)

**Comment by isholgueras** [comment]
It's already merged to master. Closing issue.
