### ISSUE TITLE
Add icons to main menu

### ISSUE THREAD

**Issue by wildwildweb** [AsociacionDrupalES/DrupalCampSpain#149]
Every menu option has an icon like in screenshot.
Thanks very much guys!!!
<img width="991" alt="captura de pantalla 2017-04-02 a las 13 02 43" src="https://cloud.githubusercontent.com/assets/592608/24584583/a8deaa4c-17a4-11e7-99fd-ca44d3c34345.png">

**Comment by nuez** [comment]
@juampynr @isholgueras Icons are already included, just need to apply the right class to the menu link. Please see the css for an overview of the classes.

**Comment by samuelsolis** [comment]
@wildwildweb  I need some icons to finish this task. Really I need a new font file with the new icon set. Then I can add to a css file.

I set the current icons using my judgment. Feel free tu suggest changes or change it for your own, the classes list is: agenda, business-day, survival-guide, speakers, sponsors, attendees, news, sprints. 

![menu](https://cloud.githubusercontent.com/assets/3817887/24670801/d1ff936a-196f-11e7-8987-2cbf09e2b29f.png)

**Comment by wildwildweb** [comment]
Hi @samuelsolis Badges must not appear in main menu, just in footer menú.

Selection criteria must not appear in main menu, if we need to show these now we must use an Article and list it in news section.

Same for proposed sessions, please use news section for this temporal content.

Tickets must not appear in main menu as normal menu item, the correct position is after How to get there in right side of the menu. 

<img width="1156" alt="captura de pantalla 2017-04-05 a las 12 06 54" src="https://cloud.githubusercontent.com/assets/592608/24689462/4e9e2484-19f9-11e7-9159-8030fce7a14e.png">

And about the CTA in a bottom special block postion:fixed all across the site must say "BUY TICKETS" not just tickets like now.

We need to keep menú clean as in the Prototype to maintain a nice and clean information arquitecture.

You can check prototype for everything: https://invis.io/XAB625QNP#/212112982_Menu
In the prototype you have the whole website finished, everything is in there.
Thanks very much and regards.

**Comment by juampynr** [comment]
@wildwildweb we discussed News at https://github.com/AsociacionDrupalES/DrupalCampSpain/issues/73 and agreed not to use them. Do you think we should get back to that and add them? Can't the footer menu be an alternative to this? Notice that I am an ignorant on these things, so whatever you suggest, we will do it.

**Comment by juampynr** [comment]
Moved badges to the footer. Pending to agree what to do with the News content type before doing anything with the rest of the menu items.

**Comment by wildwildweb** [comment]
@juampynr Sorry i forgot we dont use news... you are right!! 
So i agree about using footer menu for this content.

**Comment by juampynr** [comment]
Here is how it looks like now:

![image](https://cloud.githubusercontent.com/assets/108130/24992308/022aed70-2021-11e7-9fbd-51be3982f769.png)

Closing.

**Comment by juampynr** [comment]
I have added the Business Day and adjusted icons:

![image](https://cloud.githubusercontent.com/assets/108130/24993780/29bcd02c-2028-11e7-9e0c-2c1a54828376.png)
