### ISSUE TITLE
List attendees

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#158]
List people who bought tickets. Notice that Individual sponsors need to be listed separately.

@wildwildweb where should we list individual sponsors? They may be too many to list at the homepage. We could list a random subset of them (up to 10) in the homepage but then have a separate page to list them all. Thoughts?

**Comment by wildwildweb** [comment]
@juampynr as i know there are two different kinds of people here:

**1. Individual sponsors:** People who put money to support the AED, no just buy tickets (yes! there are crazy xD). These may be listed in individual sponsors block on prefooter.

<img width="1193" alt="captura de pantalla 2017-04-04 a las 19 51 59" src="https://cloud.githubusercontent.com/assets/592608/24655247/14137e10-1970-11e7-84cc-75b0f3e9e17f.png">


**2. Attendees:** People who buy tickets, these must be listed in custom view as we can see in the prototype: https://projects.invisionapp.com/share/JB9W60UKS#/screens/212112975

Please notice that in Attendees view there is a field that show if this person is an individual sponsor so maybe you can use same content type or user type.

![captura de pantalla 2017-04-04 a las 19 47 44](https://cloud.githubusercontent.com/assets/592608/24655183/c12548d2-196f-11e7-8089-1819abc96223.png)

But maybe i'm wrong... so you could ask Montaña to be sure.

**Comment by samuelsolis** [comment]
NOTE: Tickets with type "Individual sponsor without ticket" don't have to be showed in the attendee list.

**Comment by juampynr** [comment]
Done at https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/182.

Theming to be completed at https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/182
