### ISSUE TITLE
Add styling to the session detail page

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#161]
https://2017.drupalcamp.es/sessions/tallerworkshop-introduccion-al-desarrollo-de-modulos-en-drupal-8

![image](https://cloud.githubusercontent.com/assets/108130/24669320/3b519ae4-196a-11e7-9903-dd47c769139f.png)

**Comment by isholgueras** [comment]
If there is no one assigned to that issue I will take it tonight.

**Comment by isholgueras** [comment]
Working on it

**Comment by juampynr** [comment]
Merged https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/167
