### ISSUE TITLE
List individual sponsors

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#163]
Created out of https://github.com/AsociacionDrupalES/DrupalCampSpain/issues/158#issuecomment-291477082

**Comment by juampynr** [comment]
Created a developer app at EventBrite and figured out how to extract the data. Working on adding the listing to the homepage.

**Comment by juampynr** [comment]
Got a service that returns individual sponsors. I am now figuring out the best way to render them at the frontpage.

**Comment by juampynr** [comment]
From https://projects.invisionapp.com/share/D99TIIGHR#/screens:

![image](https://cloud.githubusercontent.com/assets/108130/24712270/b2e13afc-1a22-11e7-9d91-5878e355b82e.png)

**Comment by samuelsolis** [comment]
@juampynr I added right now a new ticket type "Individual sponsor without ticket" to allow to the non-assistant sponsorship the event.

Please get this ticket type to in the data import!

**Comment by juampynr** [comment]
TODO:

- [ ] Cache response from EventBrite.
- [ ] Response from EventBrite may have paging. Process it if so.
- [ ] List also people who bought the ""Individual sponsor without ticket" ticket.

**Comment by juampynr** [comment]
https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/174

**Comment by juampynr** [comment]
Also added caching to the response from EventBrite at https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/179.

**Comment by juampynr** [comment]
Created https://github.com/AsociacionDrupalES/DrupalCampSpain/issues/175 for the remaining item above.
