### ISSUE TITLE
Allow local mailchimp settings

### ISSUE THREAD

**Issue by nuez** [AsociacionDrupalES/DrupalCampSpain#18]
In order to create a workable Mailchimp configuration on different environments, we need to not only configure the api key, but also the ID of the Mailchimp List (mailchimp signup configuration entity).

It should be possible to use a different mailchimp signup configuration on local. However, it doesn't seem to be possible to override the mailchimp signup configuration entity in settings.php through the global $config. Any suggestions on how to do this?

**Comment by NITEMAN** [comment]
Config defined in settings.php take precedence.

We could use environment variables to inject environment dependant config. /cc @juampynr

**Comment by nuez** [comment]
It is possible to overwrite simple configurations in settings.php but it doesn't seem to be possible to overwrite configuration entities in settings.php. Possibly I just couldn't find how. see if @juampynr knows.thanks

**Comment by NITEMAN** [comment]
AFAIK, you can override any configuration in settings.php, example:
~~~
$config['system.cron']['threshold']['autorun'] = 0;
~~~

**Comment by nuez** [comment]
Thing is system.cron is a 'simple configuration' (key value) and not a configuration entity (such as mailchimp_signup). See if you can overwrite the dcamp_mailchimp configuraiton entity in settings.php

See mailchimp_signup.mailchimp_signup.dcamp_mailchimp.yml

**Comment by NITEMAN** [comment]
It is a little bit verbose, but I think it's perfectly doable:
~~~
$config['mailchimp_signup.mailchimp_signup.dcamp_mailchimp']['mc_lists']['d2ac87ce62'] = "d2ac87ce62";
$config['mailchimp_signup.mailchimp_signup.dcamp_mailchimp']['mc_lists']['5ec5525e17'] = 0;
~~~

Keep in mind we are only overriding values here, not creating new ones

**Comment by NITEMAN** [comment]
For reference: https://www.drupal.org/node/1928898

It seems that any config can be injected/overriden in settings.php

**Comment by nuez** [comment]
I had tried that option already, don't know why it didnt work for me, but it does seem to work now. thanks,

Maybe what caused the confusion is the fact that the overwritten value will never be displayed on the ConfigEntityForm, as explained in:

https://www.drupal.org/node/1928898

> You can fetch configuration without overrides to access the raw configuration value (such as to disable applying even the global overrides). This is very useful, for example if you are writing a configuration form. Using an override-free environment for the form is important, so you can avoid the values creeping in to your saved configuration. This is even more useful if your code is used in a multilingual environment, where values of your configuration are routinely overridden as translations.


See pull request: #21
