### ISSUE TITLE
How do we navigate back from certain pages?

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#194]
Since there are no breadcrumbs, a visitor can't:

1. Go back to the list of attendees when viewing an attendee:

![image](https://cloud.githubusercontent.com/assets/108130/24827941/8e852960-1c53-11e7-801d-b2075bf11b17.png)

2. Go back to the list of session proposals when reading a proposal:

![image](https://cloud.githubusercontent.com/assets/108130/24827948/aeadc1ca-1c53-11e7-8869-aeaf94b6e8b0.png)

**Comment by ckrina** [comment]
I'd say it needs a design decision regarding where and how to place a "go back" link. @wildwildweb any idea?

**Comment by wildwildweb** [comment]
Hi @ckrina I think that no back button required here. Users are web workers so every one knows how to use browser back button and hamburger menu. 

We can find hundreds of examples of top sites with a list of items and a node after click and no one use back button anymore: As example airbnb.com: https://www.airbnb.es/experiences/29469?source=p1

Anyway if we want to add some related navigation i recommend use Previous and Back pagers like in Speakers node.

<img width="1294" alt="captura de pantalla 2017-04-09 a las 11 31 58" src="https://cloud.githubusercontent.com/assets/592608/24834449/1f9255f8-1d18-11e7-8012-d3e0ebfb3f32.png">

Thanks very much and regards!!

**Comment by juampynr** [comment]
I like it short n sweet. Makes sense. Closing!
