### ISSUE TITLE
No field for image in node page

### ISSUE THREAD

**Issue by wildwildweb** [AsociacionDrupalES/DrupalCampSpain#199]
@juampynr @isholgueras sorry guys, i can't upload pictures to static pages like Badges, Survival guide, etc because there is no field for this.

Please, we need to add an image field and paint it at the header of page nodes.

![captura de pantalla 2017-04-09 a las 12 35 10](https://cloud.githubusercontent.com/assets/592608/24834790/db0854f0-1d21-11e7-9851-356e677b11d2.png)

We need different field from node body for that. Ckeditor image upload doesn't work for this because must be full width image. 

Image size is: **1876 × 534px**

You can use this module for a fast solution: https://www.drupal.org/project/fieldblock

![captura de pantalla 2017-04-09 a las 12 45 13](https://cloud.githubusercontent.com/assets/592608/24834822/4a499b62-1d22-11e7-9ba6-70071e868a44.png)

Thanks very much!!!

**Comment by isholgueras** [comment]
Added and themed in PR #202.

I reuse Image style: 1750x480. Is that enough or do we need to create a new image style? The aspect ratio is similar.

**Comment by juampynr** [comment]
Published. @isholgueras now you can add the respective images to page nodes.
