### ISSUE TITLE
Adjust header on mobiles

### ISSUE THREAD

**Issue by wildwildweb** [AsociacionDrupalES/DrupalCampSpain#200]
Some little adjustments required here to let it perfect.

<img width="674" alt="captura de pantalla 2017-04-09 a las 12 56 19" src="https://cloud.githubusercontent.com/assets/592608/24834897/31dc25a2-1d24-11e7-8452-3837300ff038.png">

![captura de pantalla 2017-04-09 a las 12 54 41](https://cloud.githubusercontent.com/assets/592608/24834900/5292f474-1d24-11e7-8701-cfeef60786a7.png)

**Comment by isholgueras** [comment]
PR #201 solves this error.
