### ISSUE TITLE
Call to action Buy Tickets

### ISSUE THREAD

**Issue by wildwildweb** [AsociacionDrupalES/DrupalCampSpain#207]
@ckrina @isholgueras @juampynr What do you think about making full width the "Buy tickets" fixed button as in attached image?

I think is going to improve the findability for this CTA because currently it seems not really easy to find.

![captura de pantalla 2017-04-09 a las 20 03 24](https://cloud.githubusercontent.com/assets/592608/24846160/eb6d1794-1dea-11e7-8a22-6813b9530e10.png)

**Comment by juampynr** [comment]
I am okay with it. Up to @ckrina, @nuez or @isholgueras to implement it.

**Comment by wildwildweb** [comment]
@juampynr @nuez @isholgueras @ckrina please remember this:
1- Change "Ticket" for something better like "Get your ticket" in this CTA and in frontpage block.
2- Add Button for "Get your tickets" in main menu after "How to get there" like in the prototype.
3- Hide this CTA in main menu because we already have the other button (number 2) in the menu.
Thanks very much!!

**Comment by isholgueras** [comment]
I made a PR #240 for this.

**Comment by juampynr** [comment]
Merged https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/240
