### ISSUE TITLE
Missing session proposals for anonymous users

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#210]
Currently, authenticated users can see 66 session proposals, while anonymous ones can only see 60.

https://2017.drupalcamp.es/sessions/proposed

**Comment by NITEMAN** [comment]
Varnish is following Drupal's cache-control headers, caching the page for 300 secs at mosts

**Comment by juampynr** [comment]
Looks good now. Did you touch anything, @NITEMAN?

**Comment by juampynr** [comment]
Fixed by magic!

http://www.reactiongifs.com/r/mgc.gif
