### ISSUE TITLE
Contact must have an image

### ISSUE THREAD

**Issue by wildwildweb** [AsociacionDrupalES/DrupalCampSpain#211]
Following invision prototype Contact must have and image.
Maybe could be a static page and the form must be a block in this page.

**Comment by juampynr** [comment]
cc @isholgueras @ckrina

**Comment by juampynr** [comment]
cc @nuez

**Comment by juampynr** [comment]
Done at https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/232/files#diff-fbefe318f8ebbd842054ede276392dd9R56

![image](https://cloud.githubusercontent.com/assets/108130/25065080/80c4bf42-2208-11e7-8681-a485b2297221.png)
