### ISSUE TITLE
Add social media icons to featured speakers, individual sponsors, and attendees

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#215]
Details at https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/193#issuecomment-293175882

**Comment by juampynr** [comment]
https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/216 removes attendee full display. Next is to add social icons.

**Comment by juampynr** [comment]
cc @wildwildweb @ckrina @nuez @isholgueras

**Comment by ckrina** [comment]
I can't work on that right now, but for the person that takes the issue: I created a "component" inside scss/components/_links.scss called .social-media with styles for this rounded icons. Reusing classes should be enough to get most of the styles.

**Comment by nuez** [comment]
I've added the icons to the attendees and the individual sponsors on the frontpage. I've made the icons a bit smaller for the attendees and even smaller for the frontpage (looks better in my opinion, otherwise the icons would be too chunky).

See #220

**Comment by juampynr** [comment]
Merged https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/220
