### ISSUE TITLE
Create user fields to get more data

### ISSUE THREAD

**Issue by samuelsolis** [AsociacionDrupalES/DrupalCampSpain#22]
This year we want to learn a little bit more about our assistants. We need some user fields to categorize the user:
All optional and all using vocabularies to allow us in the future create statistics easily.
- Role in the company (Developer, site builder, CEO, CTO, ... , Other.)
- Gender
- Country
- City (if Spain) not sure about it.

Please tag this issue as #web, it is not for the landing (and it isn't the most important task, obviously).

**Comment by NITEMAN** [comment]
Added to "register" milestone... keep in mind that if we choose eventbrite we should investigate this

**Comment by juampynr** [comment]
Now that I think about it, we may not even have a session in the site since the registration will go through Eventbrite and we will simply pull the list of subscribers via their API. Thoughts?

**Comment by juampynr** [comment]
No thoughts, closing.
