### ISSUE TITLE
Link business day block to the business day description page

### ISSUE THREAD

**Issue by samuelsolis** [AsociacionDrupalES/DrupalCampSpain#222]
The page is: https://2017.drupalcamp.es/node/35

**Comment by juampynr** [comment]
Done. Also added a link at the main menu:

![image](https://cloud.githubusercontent.com/assets/108130/24993807/3f92e198-2028-11e7-98d3-b92df8deaf06.png)

![image](https://cloud.githubusercontent.com/assets/108130/24993815/494a81be-2028-11e7-9dfa-152bc62702b1.png)

![image](https://cloud.githubusercontent.com/assets/108130/24993822/51b5ef82-2028-11e7-83e1-a5fa8a1561c6.png)
