### ISSUE TITLE
Add photo field into speaker endpoint

### ISSUE THREAD

**Issue by ccamposfuentes** [AsociacionDrupalES/DrupalCampSpain#224]
Add photo field into speaker endpoint (jsonapi/node/speaker)

**Comment by juampynr** [comment]
@ccamposfuentes Here is how you can get the photo:

https://2017.drupalcamp.es/jsonapi/node/speaker?include=field_photo

Check the output of that request and search for `included`. Is that enough for you?

**Comment by juampynr** [comment]
No feedback. Closing.
