### ISSUE TITLE
Split and link selection critera

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#229]
https://2017.drupalcamp.es/speaker-guidelines y https://2017.drupalcamp.es/es/guia-ponentes have been reviewed. Let's extract the selection criteria out of them into a separate page with its translation, and then add a link at the top of https://2017.drupalcamp.es/sessions and https://2017.drupalcamp.es/es/sessions.

**Comment by samuelsolis** [comment]
Done!
