### ISSUE TITLE
Fix the mess in Attendees list

### ISSUE THREAD

**Issue by wildwildweb** [AsociacionDrupalES/DrupalCampSpain#236]
Please, change black circle druplicon default image for this one: https://drive.google.com/open?id=0B2z682qPZOUrby04YmlRQXgwUEk

- Grey background and transparent default image when there is no user picture.
- Picture with proportional preset when there is user picture. 
(Picture must not be square!! Must look like front page speakers block. Rectangular.)

<img width="981" alt="captura de pantalla 2017-04-17 a las 12 44 37" src="https://cloud.githubusercontent.com/assets/592608/25079169/8d1c9034-236c-11e7-8fd1-fa0b088dda47.png">

Please guys fix this as soon as possible because is terrible branding.

Thanks very much!!

**Comment by juampynr** [comment]
cc @nuez

**Comment by isholgueras** [comment]
@wildwildweb, do you mean these pictures?
![image](https://cloud.githubusercontent.com/assets/140742/25117205/42dc861e-2411-11e7-881d-ea04ed1f61e9.png)
So the black one should be replaced by the image you attached in the comment? 

Thanks :)

**Comment by wildwildweb** [comment]
Yes! @isholgueras  for this one: https://drive.google.com/open?id=0B2z682qPZOUrby04YmlRQXgwUEk

And remember grey background in the view because the image is transparent..

Thanks!!!

**Comment by juampynr** [comment]
Created PR at https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/243. Need help and feedback.
