### ISSUE TITLE
Add schedule

### ISSUE THREAD

**Issue by samuelsolis** [AsociacionDrupalES/DrupalCampSpain#237]
@isholgueras in the schedule branch you have a module that print a correct HTML to theme it. 
English sessions has been marked with "eng" class.
Featured sessions has been marked with "featured" class.

We can start with this and improve the list during the week (adding level, removing the absolute link, etc).

**Comment by isholgueras** [comment]
I added this styles to the schedule. Is not ugly now, but not so pretty either...

I uploaded to the scheduler branch.

![image](https://cloud.githubusercontent.com/assets/140742/25106206/980e58ea-23c8-11e7-88c6-c511b4dc029a.png)

**Comment by juampynr** [comment]
https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/242
