### ISSUE TITLE
Improve the schedule

### ISSUE THREAD

**Issue by samuelsolis** [AsociacionDrupalES/DrupalCampSpain#244]
- Add the Juan Olalla session (I forgot it, but we have a free slot for him)
- Add a td class with the session level.
- Add a td class in the lighting sessions
- Wrap the speaker as a span and set it as a different color (pink I think).
- Theme and mark with some format using the classes added in the td elements:
  - English
  - Tag by level
  - Featured sessions
  - Ligthing sessions
 
Test it and improve the responsive behavior.

**Comment by juampynr** [comment]
Merged.
