### ISSUE TITLE
Add icons to the schedule

### ISSUE THREAD

**Issue by samuelsolis** [AsociacionDrupalES/DrupalCampSpain#250]
Add icons to sessions:
 - english
 - featured
 - Level
 - Ligthing

[schedule_icons.zip](https://github.com/AsociacionDrupalES/DrupalCampSpain/files/942000/schedule_icons.zip)

**Comment by nuez** [comment]
@samuelsolis @juampynr is there a design for this?

**Comment by samuelsolis** [comment]
Nop, @nuez,  we only have this icons to mark the session types and an imagination river :P.
