### ISSUE TITLE
Not all attendees are displayed on the website.

### ISSUE THREAD

**Issue by nuez** [AsociacionDrupalES/DrupalCampSpain#251]
I am missing myself for example.

**Comment by juampynr** [comment]
@nuez: you are only sponsoring the event, but you don't have a ticket:

![image](https://cloud.githubusercontent.com/assets/108130/25269585/8ca536ba-267d-11e7-871e-d4030dea20c2.png)

If you want to change your ticket to an individual sponsor with entrance, then talk to @samuelsolis.

**Comment by nuez** [comment]
mmm, I thought I registered both on the eventbrite website. Sorry....
