### ISSUE TITLE
[Individual Sponsor] Some user picture/avatar lost

### ISSUE THREAD

**Issue by keopx** [AsociacionDrupalES/DrupalCampSpain#254]
I bought Individual Sponsor ticket and I added the picture link,  but it is currently not shown in my sponsorship.

Here picture:
https://avatars3.githubusercontent.com/u/537583?v=3&s=460

**Comment by juampynr** [comment]
Not a bug. We just support URLs that point to actual images. See https://github.com/AsociacionDrupalES/DrupalCampSpain/blob/master/web/modules/custom/dcamp_attendees/src/Entity/Attendee.php#L117.

**Comment by keopx** [comment]
@juampynr already updated eventbrite picture url with picture with correct extension.

Thanks for explanation :+1:

**Comment by juampynr** [comment]
Awesome! Should be updated in a few minutes then.
