### ISSUE TITLE
Link the party page in somewhere

### ISSUE THREAD

**Issue by samuelsolis** [AsociacionDrupalES/DrupalCampSpain#257]
I just create the party description page (now is so simple but it can contains more information in the future), please link in somewhere :)
http://localhost/DrupalCampSpain/web/pages/party-nigth

(spanish version is available too)

**Comment by samuelsolis** [comment]
Maybe we can create an extra row in the Saturday schedule with this link and the party hour.

**Comment by juampynr** [comment]
@samuelsolis can you create it in https://2017.drupalcamp.es? And yes, the schedule seems like a good place to link to it.

**Comment by juampynr** [comment]
We could also replace Selection Criteria by Party:

![image](https://cloud.githubusercontent.com/assets/108130/25268482/2662f2ec-2679-11e7-9995-f6c4d2a80209.png)

**Comment by samuelsolis** [comment]
Lol the idea was create it in drupalcamp.es not in my local environment. Oscar did this task, it is resolved.
