### ISSUE TITLE
API

### ISSUE THREAD

**Issue by ccamposfuentes** [AsociacionDrupalES/DrupalCampSpain#258]
- Update speakers endpoint. There are just 4 speakers
- Add schedule endpoint

**Comment by juampynr** [comment]
Cool, I will have a look at this tomorrow unless I can find time today, @ccamposfuentes.

**Comment by ccamposfuentes** [comment]
@juampynr, it would be great to have it finished today. So, we can have the app done this weekend. Is that Ok with you? Thx

**Comment by juampynr** [comment]
Sure Carlos! I will do my best to get this done today.

**Comment by juampynr** [comment]
@ccamposfuentes, I realized that you have the list of spekers at https://2017.drupalcamp.es/sessions/selected?_format=json. That listing shows selected sessions along with the speaker info:

![image](https://cloud.githubusercontent.com/assets/108130/25555698/b6a1d2ea-2ced-11e7-81d1-d39590483d47.png)

Is that enough data for you?

I am creating a schedule API resource with the following structure:

```
[
  {
    time_slot,
    room,  
    session title,
    speakers,
    session_url,
    language,
    level,
    is_featured,
    is_sponsored,
  },
]
```

**Comment by ccamposfuentes** [comment]
Nice @juampynr, I'm creating the session view with this structure.

Thxs

**Comment by juampynr** [comment]
@ccamposfuentes merged this https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/274. Have a look at the README. I will push this to Production in a few minutes.

**Comment by juampynr** [comment]
@ccamposfuentes the schedule is now available at https://2017.drupalcamp.es/schedule?_format=json. Please let me know if you need anything else. Notice that I have added the event slots (such as the opening session) at the end.

**Comment by ccamposfuentes** [comment]
Hi @juampynr, i'm storing the speakers into the app and i found one problem.

Inside https://2017.drupalcamp.es/sessions/selected?_format=json  the session "Casos de éxito de Drupal en España" has many speakers whiout information (photo, dupral and twitter user, etc..).  Can you add a array of speakers into sessions?

![image](https://cloud.githubusercontent.com/assets/6200116/25563446/d23e1086-2d9c-11e7-8054-52b3c999d619.png)

**Comment by juampynr** [comment]
Me and @ccamposfuentes agreed on adding an `is_speaker` flag to the attendees list:

![selection_004](https://cloud.githubusercontent.com/assets/108130/25628004/deeb6e18-2f64-11e7-83b7-f97e4296931c.jpg)
