### ISSUE TITLE
Invidual sponsors without specific sponsor banner

### ISSUE THREAD

**Issue by keopx** [AsociacionDrupalES/DrupalCampSpain#262]
Invidual sponsors without specific sponsor banner

https://2017.drupalcamp.es/attendees/list?page=1

![attendees drupalcamp spain 2017](https://cloud.githubusercontent.com/assets/537583/25436021/42b2a056-2a92-11e7-8545-3ddfb4296a64.png)
![sponsor](https://cloud.githubusercontent.com/assets/537583/25436020/42ae14aa-2a92-11e7-9607-c3dee3c5b48b.png)

**Comment by juampynr** [comment]
We just implemented this for attendees that bought the special ticket "individual sponsor attending to the event" ticket. For attendees that bought an attendee ticket and then an "individual sponsor not attending to the event" we did not write the logic to relate the two tickets and show this banner.
