### ISSUE TITLE
Add WildWildWeb logo to Sponsors

### ISSUE THREAD

**Issue by wildwildweb** [AsociacionDrupalES/DrupalCampSpain#268]
Please upload this new sponsor.
https://wildwildweb.es/
![logo](https://cloud.githubusercontent.com/assets/592608/25488205/1d037c30-2b6f-11e7-926c-0eb11f94cbde.png)

[logo.svg.zip](https://github.com/AsociacionDrupalES/DrupalCampSpain/files/961905/logo.svg.zip)
Thanks!

**Comment by juampynr** [comment]
Pardon my ignorance but I don't know how to covert an svg to a png or jpg. @wildwildweb: are you happy with how the log looks like at https://2017.drupalcamp.es ?

**Comment by wildwildweb** [comment]
@juampynr thanks!!! Could be a little small? Now it's too big..

**Comment by juampynr** [comment]
I think that it is because the image has no margins. I fear that I will mess it up. Do you mind sending me another image with bigger whitespace area?

**Comment by wildwildweb** [comment]
@juampynr could you give me access to edit sponsor nodetype and a take care of this and also i can  resize the rest of the logos to homogenize them? I would like to resize all of them for better vertical alignment.

**Comment by juampynr** [comment]
Done! I have made you admin.

**Comment by nuez** [comment]
I think you can solve this in CSS.

**Comment by wildwildweb** [comment]
@nuez thanks!! anyway we are uploading all new logos to make all fit perfect.

**Comment by nuez** [comment]
@wildwildweb @juampynr If the logos look good without this PR, I suggest that we don't merge it so we don't accidentally break anything.

**Comment by wildwildweb** [comment]
@nuez @juampynr it's doesnt look good!! 
We upload all logos with same height.
Now would be nice to change the css in order to vertical alignment of all logos (see attachments).
![captura de pantalla 2017-04-28 a las 16 52 04](https://cloud.githubusercontent.com/assets/592608/25534094/747c0762-2c3b-11e7-9688-90fef841ea29.png)
![captura de pantalla 2017-04-28 a las 16 52 11](https://cloud.githubusercontent.com/assets/592608/25534095/74828600-2c3b-11e7-8831-448a0f701d8f.png)

**Comment by juampynr** [comment]
@nuez would your PR fix that?  ^

**Comment by nuez** [comment]
Now it would
