### ISSUE TITLE
Landing page: General amends

### ISSUE THREAD

**Issue by salvamomo** [AsociacionDrupalES/DrupalCampSpain#27]
"Stay informed" section: 
- Email can't be entered (form markup indicates it's disabled, this might be on purpose until launch?). 
- Also, "Submit" button text gets pushed to the bottom right corner of the button square when displayed on mobile.

- "ORGANIZA": Text appears in Spanish also when seeing the landing page in english. Same with the "Contacto" link. 
- Additionally, there's not enough vertical space between the links when displayed on mobile.

**Comment by nuez** [comment]
Fixed in #34. Organiza is now a translatable string (still has to be translated in the interface)
