### ISSUE TITLE
Infinite pager in Attendees and Speakers views

### ISSUE THREAD

**Issue by wildwildweb** [AsociacionDrupalES/DrupalCampSpain#272]
As specified here: https://projects.invisionapp.com/d/main#/projects/boards/5217168

<img width="908" alt="captura de pantalla 2017-04-28 a las 18 33 35" src="https://cloud.githubusercontent.com/assets/592608/25535839/27f3e8dc-2c41-11e7-9414-fc939c5f600f.png">

**Comment by juampynr** [comment]
We did not implement this feature.
