### ISSUE TITLE
Set up 2018 theme

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#291]
@nuez, I see the following dir structure:

![image](https://user-images.githubusercontent.com/108130/33178735-6890db8c-d067-11e7-9948-19600b6900cf.png)

`dcamp_2017_landing_theme` extends `dcamp_2017_theme`, which extends `dcamp_base_theme`.

Shall I create `dcamp_2018_theme` and `dcamp_2018_landing_theme`?

**Comment by juampynr** [comment]
Alternativelly, can't we:

1. copy `dcamp_2017_landing_theme1` to `dcamp_landing_theme`.
2. copy `dcamp_2017_theme` to `dcamp_theme`.

And then in a future release, remove the 2017 directories? Then for 2019 we would only need to edit the dcamp_landing_theme and dcamp_2017_theme directories.

@nuez, please just give me some instructions on how to proceed. I am okay about going the easy route if changing things takes a lot of effort.

**Comment by nuez** [comment]
I would use the dcamp_2018_theme and dcamp_2018_landing_theme format. Just copy the two 2017 themes to the 2018 equivalents, and from there we'll adjust the theming. That would be more consistent.
