### ISSUE TITLE
Tweak colors, fonts etc to make Dcamp 2018 more specific

### ISSUE THREAD

**Issue by nuez** [AsociacionDrupalES/DrupalCampSpain#297]
We could make minor changes to the look and feel of the dcamp 2018 theme to make it more 'unique' for the Alicante version. Maybe just changing some colors and maybe the font would be enough.

Is this a good idea?

**Comment by juampynr** [comment]
I don't have an opinion about this. Thoughts @ferelx?

**Comment by ferelx** [comment]
Actually that was my intention, to play with colors, images and typographies. Especially highlight beautiful images of Alicante, to attract potential public

**Comment by juampynr** [comment]
Let's go with what we have for the landing. Closing.
