### ISSUE TITLE
Landing Page: Footer Newsletter Button

### ISSUE THREAD

**Issue by AntonioGarRod** [AsociacionDrupalES/DrupalCampSpain#33]
Wrong text alignment newsletter footer suscribe button on responsive, tested on:
* Nexus 5x
* Nexus 6p
* Iphone 5
* Iphone 6

![screenshot from 2016-09-24 16-52-43](https://cloud.githubusercontent.com/assets/3091045/18809284/70c56546-8277-11e6-83e3-28b7d527ae80.png)

**Comment by nuez** [comment]
Fixed in https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/34
