### ISSUE TITLE
Error on google search results

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampSpain#331]
![screenshot from 2018-03-26 13-55-58](https://user-images.githubusercontent.com/877002/37904954-974aea70-30fd-11e8-9599-171acc8a4f03.png)

Found by psf_ on IRC

**Comment by PSF1** [comment]
Hi, I'm psf_ XD

**Comment by juampynr** [comment]
This was caused by a wrong translation which we fixed last week. I guess that we just need to wait for the google bot to visit the site again and re-discover it unless there is a way to force it to.

**Comment by juampynr** [comment]
Also, thanks for the heads up to both of you!

**Comment by juampynr** [comment]
Looks good to me now:

![image](https://user-images.githubusercontent.com/108130/40167939-9fd6f006-59c2-11e8-9f99-101380dce1b3.png)
