### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampSpain#332]
GitHub says that we have some vulnerabilities on our code:
![screenshot from 2018-03-26 13-56-44](https://user-images.githubusercontent.com/877002/37904996-bdf093aa-30fd-11e8-8f65-b7e591bc7d00.png)

**Comment by juampynr** [comment]
@nuez have you ever seen this? Need your help as I don't know what packages to update.
