### ISSUE TITLE
There is an error with link to a drupal speaker page.

### ISSUE THREAD

**Issue by alonsomaniaco** [AsociacionDrupalES/DrupalCampSpain#335]
If we access [here](https://2018.drupalcamp.es/sessions/docker-subete-al-barco-de-las-herramientas-de-desarrollo-estandar-marinero) and click on Drupal speaker page, dimaro in this case, link has an space and it shows a 404.
Piece of code taken from site:
`<a href="https://www.drupal.org/u/ dimaro" class="social-media__link--drupal"></a>`

**Comment by juampynr** [comment]
They had filled up the Drupal.org field as `marinero / dimaro`. I have just set it to `dimaro`.

Thanks for the heads up!
