### ISSUE TITLE
Sponsor problem

### ISSUE THREAD

**Issue by PSF1** [AsociacionDrupalES/DrupalCampSpain#336]
Hi,

My business paid a sponsorship but don't appear in the web, where we can contact for this?

Thanks

**Comment by juampynr** [comment]
Hi Pedro!

I am checking it with the Spanish Drupal Association.

**Comment by PSF1** [comment]
Thanks, the business is SDOS.

**Comment by alvar0hurtad0** [comment]
So sorry for the delay.

I've just published the logo and also on drupal.es.

Please, @PSF1 close the issue if looks good to you.

**Comment by PSF1** [comment]
Thanks so much :))
