### ISSUE TITLE
Sponsor label does not appear on attendees list

### ISSUE THREAD

**Issue by nachosalvador** [AsociacionDrupalES/DrupalCampSpain#341]
Noticed a case which does not appear:

* Buy individual ticket using speaker's coupon.
* Buy sponsor ticket.

**Comment by juampynr** [comment]
Fixed https://2018.drupalcamp.es/attendees/list?page=1
![image](https://user-images.githubusercontent.com/108130/40427777-ef067b98-5e9e-11e8-88fe-92434a50ba13.png)
