### ISSUE TITLE
Dates should apear in the landing

### ISSUE THREAD

**Issue by NITEMAN** [AsociacionDrupalES/DrupalCampSpain#38]
Landing page does not contain Drupalcamp's date

/cc @nuez @juampynr

**Comment by juampynr** [comment]
@wildwildweb, ¿podríais adjuntar aquí las imágenes con las fechas para que las reemplacemos en la web?

![image](https://cloud.githubusercontent.com/assets/108130/19694608/0b7b32a2-9aae-11e6-9dce-345f05d7e50f.png)

**Comment by wildwildweb** [comment]
@juampynr aquí la tienes, es un solo svg.
[logo.svg.zip](https://github.com/AsociacionDrupalES/DrupalCampSpain/files/551279/logo.svg.zip)

**Comment by juampynr** [comment]
Gracias!

**Comment by nuez** [comment]
See #45 

This logo added by @wildwildweb isn't right, it shows vertical white bars where the gradient is. I've used it to change the already existing logo.

I haven't added a $_GET query to the logo (logo.svg?pleasedontusecache=123), @NITEMAN would that be necessary?

**Comment by wildwildweb** [comment]
@nuez you are right! Sorry! I attach the good one
[logo.svg.zip](https://github.com/AsociacionDrupalES/DrupalCampSpain/files/583975/logo.svg.zip)

.

**Comment by juampynr** [comment]
Merged https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/45
