### ISSUE TITLE
Sesión incorrecta

### ISSUE THREAD

**Issue by luisortizramos** [AsociacionDrupalES/DrupalCampSpain#386]
Buenas tardes,

Soy Luis Ortiz Ramos, mi sesión "Configurando una librería de medios en Drupal 8" fue seleccionada y agendada pero aparece con el nombre incorrecto en la agenda, pone: "CWG - who, what, where, how by Luis Ortiz Ramos".

¿Podeis revisarlo?

Muchas gracias,

PS: Envié esto mismo usando el formulario de contacto pero no he tenido respuesta ni ha habido mejora, disculpadme por el doble envío.

**Comment by rteijeiro** [comment]
PR merged en dev. Listo para despliegue.

**Comment by capynet** [comment]
Parece solucionado. Gracias por reportar. Cierro!

**Comment by luisortizramos** [comment]
Genial, gracias!
