### ISSUE TITLE
Añadir logo

### ISSUE THREAD

**Issue by jlbellido** [AsociacionDrupalES/DrupalCampSpain#400]
**Acceptance Criteria**
Como visitante quiero poder ver el logo del evento en la landing de la web del evento.

**Información addicional**
Diseño de este año: https://trello.com/c/LWBgBKkP/26-dise%C3%B1o-landing

- [x] Añadir logo final a esta tarea.
- [x] Añadir logo y maquetar en el tema comming_soon_th.

**Comment by pcambra** [comment]
https://www.figma.com/file/Wk4cEQWD1fKdtJZfH0pL38/DrupalCamp-Spain?node-id=0%3A1

**Comment by jlbellido** [comment]
Creo que podemos cerrar esta tarea. Mil gracias @pakmanlh @pcambra
