### ISSUE TITLE
Cambios pendientes en la landing

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#42]
De un correo de César:

En ambos idiomas:
- [x] Última sección: Linkar Twitter a la cuenta de la camp: https://twitter.com/drupalcampspain (ahora enlaza al perfil de la AED)
- [ ] Mantente informado: Las bolitas del pager tienen que ser azules (#4b26e6) ya que ahora son del mismo color rosa del fondo y el pager deja de verse.

En el sitio en ESPAÑOL:
- [x] Conviértete en patrocinador: Traducir el botón “Download the PDF” a “Descargar dossier” o “Descargar dossier de patrocinadores"
- [x] Únete a la AED: Traducir el botón "Join the Spanish Drupal Association" por “Unete a la Asociación Española de Drupal”
- [x] Mantente informado
  · Traducir el label "Subscribe to the newsletter” por “Suscribete al newsletter"
  · Traducir el placeholder “Your email” por “Tu email"
  · Traducir el botón “Submit” por “Enviar”
  · Traducir el texto “Don't worry, we won't spam you.” por “Tranqui, no te freiremos a spam” (con este tono madrileño y simpático ;-)
- [x] Última sección: Traducir “Organized by” por “Organizado por"

**Comment by juampynr** [comment]
>Mantente informado: Las bolitas del pager tienen que ser azules (#4b26e6) ya que ahora son del mismo color rosa del fondo y el pager deja de verse.

@wildwildweb, ¿qué bolitas?

**Comment by juampynr** [comment]
@wildwildweb: he hecho el resto de cambios. ¿Puedes verificarlos en http://2017.drupalcamp.es?

**Comment by wildwildweb** [comment]
Todo bien Juampy! Muchas gracias!
Las bolitas son el pager que no se ve en el bloque rosa porque es del mismo color del fondo.
Adjunto captura.
![bolitas](https://cloud.githubusercontent.com/assets/592608/19800886/2c51596a-9cfd-11e6-8293-c5bde449cd66.jpg)

**Comment by wildwildweb** [comment]
He detectado otra pijada que falta por traducir, la cuenta atrás (Days, Hours, Minutes) aparece siempre en inglés. Gracias!

**Comment by nuez** [comment]
See #47:

It solves the bullet point color, although not exactly the 4b26e6 color code, but a tad darker, to differentiate from the blue background on one of the sections.

When it comes to translating the strings (they are already translatable): we need to create a user that is able to do that type of admin stuff: See #48

**Comment by juampynr** [comment]
Cierro. He creado #49 para corregir el idioma de la cuenta atrás.

**Comment by juampynr** [comment]
@nuez, ¿ves tú el pager de bolitas que menciona @wildwildweb en http://dev.drupalcamp.es? Yo no lo veo.

**Comment by nuez** [comment]
Yo los veo pero difícil en las primeras pantallas.

Los cambie con las indicaciones de @wildwildweb, un pelín más oscuro para verlos sobre fondo azul. Vamos a tener el problema con el fondo y los bolitos, si siguien siendo morados o azules, con los fondos que tenemos. O tenemos que cambiar el color según hagamos scroll, que me parece un poco lío. 

@wildwildweb qué propones?

**Comment by juampynr** [comment]
Cerramos. @wildwildweb, si queda algo pendiente, abre una nueva issue por favor.
