### ISSUE TITLE
Create user 'editor'

### ISSUE THREAD

**Issue by nuez** [AsociacionDrupalES/DrupalCampSpain#48]
Create a user that can do basic admin stuff such as

- translate interface
- create content (later on)

There is already a role 'editor' that should provide for the permissions.

**Comment by juampynr** [comment]
@nuez, ready for review.

**Comment by nuez** [comment]
How do I test this,? I don't have the user 1 login for Dev. Should the username and pass be published on trello so people can start translating stuff and editing content?

**Comment by juampynr** [comment]
There is not much to test, I just configured permissions in prod but have not created editors yet. For security I prefer that each person has its own account rather than having a generic editor account.

**Comment by nuez** [comment]
In that case, Can you add me as editor?

**Comment by juampynr** [comment]
you are editor and admin. Didn't you get an email?

**Comment by juampynr** [comment]
I thikn that cron takes care of that. I just triggered it.

**Comment by nuez** [comment]
@juampynr I didn't get an email, but no worries, i'll try to get an one time login link tomrrow

**Comment by juampynr** [comment]
@NITEMAN, how can we verify that emails are going out of http://drupalcamp.es? Yesterday I created a few accounts including yours.

**Comment by juampynr** [comment]
Fixed via #48.

**Comment by NITEMAN** [comment]
@juampynr the server log shows a mail for me received by google:
```
Feb 14 07:37:57 aed01 postfix/cleanup[26633]: 4C49F5160AC2: message-id=<20170214063757.4C49F5160AC2@aed01.asociaciondrupal.es>
Feb 14 07:37:57 aed01 postfix/qmgr[3216]: 4C49F5160AC2: from=<drupalcamp@drupal.es>, size=1222, nrcpt=1 (queue active)
Feb 14 07:37:57 aed01 postfix/smtp[26635]: 4C49F5160AC2: to=<nit****@gmail.com>, relay=gmail-smtp-in.l.google.com[2a00:1450:400c:c08::1a]:25, delay=0.56, delays=0.11/0/0.09/0.36, dsn=2.0.0, status=sent (250 2.0.0 OK 1487054277 c13si2191141wmi.71 - gsmtp)
```

**Comment by juampynr** [comment]
@NITEMAN see https://github.com/AsociacionDrupalES/DrupalCampSpain/issues/64
