### ISSUE TITLE
Implement navigation menu

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#51]
Based on https://projects.invisionapp.com/boards/V233TLCG5W4KU, implement the top navigation. This is a floating menu that expands on click.

**Comment by ckrina** [comment]
I'm not aware about any outside-in library or pre-build feature that implements this. I'd create & animate a new region with all this elements and maybe I'd add the trigger into the header.
I guess my first approach would be to animate region's left position toggling a class. And I would play with vw measure for element's with.
I'll try to find an example to share it here.

**Comment by juampynr** [comment]
Thanks @ckrina!

**Comment by nuez** [comment]
Not worth the hassle of an external library, it should do with some CSS and a toggling class at <body> level. I have a 2 hour train journey coming up, I'll give it a go.

**Comment by juampynr** [comment]
This is done. Now we need to create the contents so we can add links to it.
