### ISSUE TITLE
Survival Guide

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#52]
This page contains everything about the city and the venue. Further details can be found at https://docs.google.com/document/d/1xnhDybBHu7nLikagIN6Nxw3lf9zQLDrL9JUPE0sJUj4/edit#.

**Comment by samuelsolis** [comment]
We don't have an specific design for this page but we already have a home page design. I think that it's useful refer it here.

Desktop design can be found in this [here] https://projects.invisionapp.com/share/D99TIIGHR#/screens)

Mobile adaptation can be found [here](https://projects.invisionapp.com/share/2E9UFP9TB#/screens)

Some style consideration (Please read before start the task) can be found [here](https://projects.invisionapp.com/boards/V233TLCG5W4KU/)

**Comment by juampynr** [comment]
I just created an unpublished node with the contents https://2017.drupalcamp.es/node/1. Reviews are welcome. For the moment it just contains transport and logistics.

**Comment by juampynr** [comment]
I am tempted not to cover these sections in the survival guide:

- Sobre el evento: http://2016.drupalcamp.es/es/node/257: we don't know what to say yet.
- Sobre la ciudad: http://2016.drupalcamp.es/en/content/about-city: I don't think that we can put anything valuable here. Thoughts?
- Badges: http://2016.drupalcamp.es/en/content/badges: do we have them?

**Comment by samuelsolis** [comment]
@juampynr I just reviewed it. For me it's correct, some notes about it: 

I think that we have to contact with 2/3 hotels to make as a official hotels (for concentrate all drupal people as posible in the same zone) and added it to this section.

I added car2go and Emov as a car sharing services to use in Madrid.

I think that it's important to dedicate some paragraph to describe the leisure in Madrid and some things to do. Not a large description, just a little mention. I added it too.

Please review it (and review my poor english too :_( sniff ).

**Comment by juampynr** [comment]
> I think that we have to contact with 2/3 hotels to make as a official hotels (for concentrate all drupal people as posible in the same zone) and added it to this section.

Created https://trello.com/c/cJn3pdfj/21-contactar-con-dos-hoteles-cerca-de-la-casa-encendida-para-que-nos-hagan-descuento-y-que-los-asistentes-y-featured-se-alojen-alli cc @isholgueras @NITEMAN 

> I think that it's important to dedicate some paragraph to describe the leisure in Madrid and some things to do. Not a large description, just a little mention. I added it too.

I feel that this is a waste of time. We have done it in the past, but nowadays there is little that we can say about Madrid. However, we can give a few ideas of what you can do in the area where DrupalCamp is taking place, right? I could add a section about that.

**Comment by juampynr** [comment]
@samuelsolis, I have removed the section about Madrid (sorry, it's a survival guide, so let's focus in the useful stuff).

I have also created and linked a map with useful points around the area.

@nuez @ckrina what's the best way to add styles to a node? It's this one https://2017.drupalcamp.es/node/1.

**Comment by juampynr** [comment]
cc @wildwildweb

Here is how the [Survival Guide](https://2017.drupalcamp.es/node/1) looks like:

![image](https://cloud.githubusercontent.com/assets/108130/23146299/d7ad1460-f7d5-11e6-8fd8-59517e488af5.png)

All of you have accounts at https://2017.drupalcamp.es (check your spam).

**Comment by ckrina** [comment]
I've reviewed the designs and the styles are the same in most of the details (survival, news detail, Business day), so I guess we could create them as general styles for node detail.

**Comment by juampynr** [comment]
Cool, so we need to add theming to the page default view mode.

**Comment by samuelsolis** [comment]
I added a link to this guide (http://wikitravel.org/en/Madrid). I read it and it seems ok and it's like a wiki without any company around.

**Comment by juampynr** [comment]
This is getting better! Now it looks like this in master:

![image](https://cloud.githubusercontent.com/assets/108130/23600835/d0621016-0248-11e7-960c-de2820c2cb2b.png)

cc @nuez @ckrina

**Comment by nuez** [comment]
@juampynr Do we need to do more here?

**Comment by juampynr** [comment]
@nuez yes, we need a db update that publishes it plus I don't know how we can promote this at the new homepage. Shall we add a block? Does it need a menu item?

cc @ckrina @wildwildweb

**Comment by nuez** [comment]
Menu item can be added, according to the design. If you use the class 'business-day' in the menu link, The icon will be added automatically. Check the corresponding SCSS file for the for the class name, but i think it's business-day

**Comment by juampynr** [comment]
This node should be linked from the block about the venue like this:

![image](https://cloud.githubusercontent.com/assets/108130/23990016/f97b1990-0a34-11e7-8e34-08557771be4e.png)

Source https://projects.invisionapp.com/share/2RAV3M7VX#/screens/212112981_Home

**Comment by nuez** [comment]
You can add the link by including the following HTML:

<a href="link-to-guide" class="button">Guía de supervivencia</a>

**Comment by juampynr** [comment]
https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/104
