### ISSUE TITLE
Business Day

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#53]
This is a section of the homepage with info about the Business Day. There is a design example at https://projects.invisionapp.com/boards/V233TLCG5W4KU/.

As for the contents, I don't know where to get them from. @monfranco, @ckrina: any ideas?

**Comment by nuez** [comment]
For theming it would be good if this page can be created. There is default theming present, that I've also added to nodes of type articles.

**Comment by juampynr** [comment]
Since it is not clear yet what we will do, I added a link to the Contact form if people are interested https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/108.
