### ISSUE TITLE
Configure performance settings

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#54]
Based on the following screenshot:

![image](https://cloud.githubusercontent.com/assets/108130/22774821/198b37ee-eea9-11e6-8d7f-806bc5374563.png)

1. We need to test locally whether aggregating CSS and JS does not break the design.
2. @NITEMAN, shall we set cache lifetime or is this handled via Varnish?

**Comment by NITEMAN** [comment]
@juampynr you should set it, something like 5 minutes would be fine.

I can create a jenkins job to clear Varnish for convenience and modify ansistrano deploy accordantly.

**Comment by juampynr** [comment]
@NITEMAN please check https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/63

**Comment by juampynr** [comment]
Merged #63. Assigning to @NITEMAN to update the deploy job.
