### ISSUE TITLE
Gather all icons and background SVG and put them in fontello

### ISSUE THREAD

**Issue by nuez** [AsociacionDrupalES/DrupalCampSpain#56]
We need all the icons used in the design and include them in our fontello icon font.

This issue should also include putting background images and patterns in the appropriate folder.

**Comment by wildwildweb** [comment]
Link to Drive folder with icons: [https://drive.google.com/open?id=0B5Zv1LP5pgikcTZGTE5qS2ZmYUE](url)

**Comment by samuelsolis** [comment]
![fontello_error](https://cloud.githubusercontent.com/assets/3817887/22900521/df59b18e-f22e-11e6-9331-deb2d41a51ea.png)

I tried to upload it but Fontello throw me some errors (see attached image). I tried dragging only the little svgs (dropping the logo and the big letters) but the errors were thrown  again. I don't know the problem with the svg, somebody can help me or try to do it? The font can be attached here.

**Comment by nuez** [comment]
You possibly need to edit the svg in illustrator so that it its black and transparent exclusively (no line, but solids) by useing compound paths only.

**Comment by nuez** [comment]
@wildwildweb Can you confirm that you've uploaded all the images, it seems that we're missing some icons for the menu items?

**Comment by wildwildweb** [comment]
@nuez i confirm that we don't upload all the images and the svg's are in wrong format. We'll fix it today. Sorry about that.

**Comment by wildwildweb** [comment]
@nuez @samuelsolis i uploaded all images here: [https://drive.google.com/open?id=0B5Zv1LP5pgikVmc3bUNUeGNWMUU](url)
As far as I know, not all images and icons can be inserted in a fontfile. Just flat images can be. 
We have complex images with gradients and different forms like for example the logo that cannot be inserted in the font.
We put images in 3 different folders.
Maybe you can find the way, but i think it's so much fast and easy go forward without the font and use svg directly. We (Me and Iván) can't spent more time on this, so, guys, it's up to you.

**Comment by samuelsolis** [comment]
I tried again and the font generated doesn't seem correct. But.. I don't know how is the correct way because I never used it again. @nuez please, can you try to create the font using the svg posted above? If you know how to do it.

If it's a svg problem I suggest forget fontello and use directly the svg image. I know that it isn't the recommended way but this is a very little project and it will be over in 4 months, a month after the Drupalcamp finish.

**Comment by nuez** [comment]
@samuelsolis The idea was to use this as a blue print for future websites (I know it will probably never happen) Anyways, I've added the icons to the font that we can use for icons, in #59. Let me try to add them to the new menu tomorrow as I will have some train journeys and flights,

Advantage of fonts is that we can change colors, even add gradients, also is easier for adding to text with the :after or :before statement.

I agree that the rest of the images probably better as svg. thanks @wildwildweb !

**Comment by juampynr** [comment]
@nuez, @samuelsolis, is ther still anything to do here? If not, shall we close this?

**Comment by samuelsolis** [comment]
Yeah, I toke a look to #59 and he already uses a icon font. I suppose that he could add it correctly.
