### ISSUE TITLE
List of sponsors

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#62]
Create a simple content type that holds the title, URL and logo of each sponsor.

Place sponsors at the homepage. Create a block for gold sponsors and a block for silver sponsors.

**Comment by juampynr** [comment]
This is blocked until we get a list of each sponsor title, it's url and its logo.

cc @monfranco

**Comment by samuelsolis** [comment]
I just created a content type with title, url, logo and type field (to choose between silver, gold, etc) and a block view with a list of sponsors filtering by type. Currently only two displays: for silver and for gold sponsor types.

I created a image style to render the logo correctly. 

The task isn't finished yet (it aren't themed) but the backend seems complete.

I have this (partial) solution in my fork in this branch: https://github.com/samuelsolis/DrupalCampSpain/tree/62sponsors

How can I attach it here for sharing? I know the way to create a new pull request opening a new issue but no the way to create a pull request for resolving an existing issue. Thanks guys!

**Comment by nuez** [comment]
Just create the pull request and refer to it in a comment. Thanks!

**Comment by samuelsolis** [comment]
Thanks nuez! done!

**Comment by nuez** [comment]
@samuelsolis @juampynr 

We still need a view ordered by categories of the sponsors. It would be good to have it already even if we don't have any actual content so I can place it in the homepage.

**Comment by samuelsolis** [comment]
@nuez A single view with all sponsors ordered by sponsor type? Ok! I will try to it do this afternoon!

**Comment by nuez** [comment]
Yep that's it! It would be good if every section can have a HTML class based on the sponsor type. Not sure if that's possible with views. I think so. (If not i'll just use nth-child)

**Comment by juampynr** [comment]
We got the main logic working. There is a follow-up at https://github.com/AsociacionDrupalES/DrupalCampSpain/issues/102.

Closing.
