### ISSUE TITLE
Review email configuration

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#64]
Turns out that emails are getting to the spam folder:

![image](https://cloud.githubusercontent.com/assets/108130/23055701/85e661a4-f4e7-11e6-8022-0359306bb022.png)

@NITEMAN, can you review the email settings in production?

**Comment by juampynr** [comment]
@NITEMAN, remainder.

**Comment by NITEMAN** [comment]
I've routed all server's mail through mailgun.

I've also requested a pasword reset for you @juampynr , please confirm it reached your regular inbox. If not, please re-open.

**Comment by juampynr** [comment]
Got it! Thanks @NITEMAN.
