### ISSUE TITLE
Featured speakers

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#67]
We need a content type to promote featured speakers. This should have:

Name
Bio
Twitter
Company URL
Photo

**Comment by nuez** [comment]
BTW this is something that someone could take over, as it's pretty stand alone. We should ask in the group if anyone wants to help us with this, people that have said to help in the past: Salva, Antonio...

**Comment by ckrina** [comment]
Regarding to comments in #76 

> for the full node we should focus on the image and background

I'm not sure if the idea for the top main image is doing something else to it. When I talked with César his idea was to create manually speaker's images with the colored background.

**Comment by juampynr** [comment]
This is done. Let's create new issues/PRs for next steps.
