### ISSUE TITLE
Submit your session block

### ISSUE THREAD

**Issue by samuelsolis** [AsociacionDrupalES/DrupalCampSpain#69]
Determine a way to submit sessions and implement it.

The block will be placed in the homepage.

Related:
https://github.com/AsociacionDrupalES/DrupalCampSpain/issues/66

**Comment by nuez** [comment]
Should be this eform or similar, or even a custom content entity? I don't have much experience with form modules in D8. I do know that it could be as simple as a custom content entity, which would be my prefered solution unless there is a module that works out of the box.

**Comment by juampynr** [comment]
Form? No form, I suggest (keeping in mind Short'n Sweet) to use a Trello to manage the call4papers as we discussed a few weeks ago. See https://paper.dropbox.com/doc/Call4Papers-Trello-vs-Drupal-oqFeT29K1Zf0L3y04YqkQ for further details.

**Comment by juampynr** [comment]
Follow up at https://github.com/AsociacionDrupalES/DrupalCampSpain/issues/95

Closing.
