### ISSUE TITLE
Create a Newsletter block

### ISSUE THREAD

**Issue by samuelsolis** [AsociacionDrupalES/DrupalCampSpain#71]
Create a Newsletter block to be placed in the homepage.

Related:
https://github.com/AsociacionDrupalES/DrupalCampSpain/issues/66

**Comment by juampynr** [comment]
Isn't enough with the one that we have already at the homepage or is this one that will go in a sidebar?

![image](https://cloud.githubusercontent.com/assets/108130/23146254/650c331e-f7d5-11e6-869b-e21f316e2dd3.png)

**Comment by nuez** [comment]
This should go in the footer See, #75

**Comment by samuelsolis** [comment]
Ok we can use this block and theming in the footer. Can we close this issue? I'm reviewing all 1.0 milestone and seems too near to be closed!

**Comment by nuez** [comment]
I've already incorporated this in the footer.
