### ISSUE TITLE
News list

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#73]
We need a News content type in order to promote things in the site. We could:

* [x] Adjust the Article content type.
* [x] Create a view of articles.
* [ ] Theme news view.
* [ ] Theme article full.

**Comment by juampynr** [comment]
@wildwildweb, how could we show latest news in the homepage?

**Comment by wildwildweb** [comment]
@juampynr ok! i will try to get this done before friday.

**Comment by juampynr** [comment]
Moving this to the next milestone since @wildwildweb will be out this week.

**Comment by juampynr** [comment]
@wildwildweb, we have the content type and view in place. Now we need the designs in order to apply the theming.

https://github.com/AsociacionDrupalES/DrupalCampSpain/issues/74

**Comment by juampynr** [comment]
I am starting to think that we don't need this.

Thoughts @samuelsolis @isholgueras @wildwildweb @ckrina ?

**Comment by ckrina** [comment]
We usually use this to announce the starting and end dates for the call for paper, change of ticket prices... but not much more. And we already have some blocks to explain it. I don't have a strong opinion, but it have sense not developing it.

**Comment by samuelsolis** [comment]
I think that we can work in things that are really important, it can be prescindible as Cristina say.

But if we don't develop it we have to pay attention to put the start/end date in the call4paper block and the others stuff.

**Comment by juampynr** [comment]
Awesome. Closing then. Thanks.
