### ISSUE TITLE
Create footer

### ISSUE THREAD

**Issue by nuez** [AsociacionDrupalES/DrupalCampSpain#75]
Add the correct blocks to footer region for all pages.

**Comment by nuez** [comment]
Blocks that go in the footer: 

- newsletter
- social links Twitter and FB (can be hardcoded as far as i'm concerned)
- Main menu
- Second menu
- (c) statement

**Comment by juampynr** [comment]
@nuez where is this in the design? What do you mean by "right blocks to footer region?"?

**Comment by nuez** [comment]
https://projects.invisionapp.com/share/D99TIIGHR#/screens

I assume that the blocks mentioned above go in a general footer visible on all pages. 

I meant 'add the correct blocks'

**Comment by juampynr** [comment]
Gotcha! Thanks.

**Comment by juampynr** [comment]
@nuez the landing theme is still active in prod (https://2017.drupalcamp.es/admin/appearance):

![image](https://cloud.githubusercontent.com/assets/108130/23201807/858b4948-f8db-11e6-8148-e0df9a279475.png)

Shall we deactivate it for 1.0? If so, we need a database update to do the switch. Also, shall we create the new blocks under `themes/dcamp_2017_theme` ?

**Comment by nuez** [comment]
Correct, the landing page will still work since I build it with a themenegotiatior that will select the theme based on the settings in /admin/structure/dcamp/2017/edit. I would keep the theme active, just not default.

**Comment by nuez** [comment]
See #86

**Comment by nuez** [comment]
This was merged
