### ISSUE TITLE
Support collaborators as a sponsor type

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#84]
See https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/77#issuecomment-283292430 for details.

**Comment by nuez** [comment]
This is really just a config change of the field. Can you pick this up @samuelsolis?

**Comment by samuelsolis** [comment]
Yeah! sorry.

Yes, it can be an extra sponsor level. I'm going to fix it.
