### ISSUE TITLE
Change LCE background

### ISSUE THREAD

**Issue by isholgueras** [AsociacionDrupalES/DrupalCampSpain#85]
Hi,

I wrote an [issue in trello](https://trello.com/c/DYIs0Otk/28-imagen-de-lce-en-web-no-permitida), but I'll write it here too.

It's important and kind of urgent because of internal policies of LCE. Pablo R. wrote me again to remove or change the background image.

Can we do it before the launch of the new version?

Thanks

**Comment by juampynr** [comment]
Sure, I will do that today.

**Comment by isholgueras** [comment]
Hi @juampynr,

Here you have the location.jpg for replace the old one: ![location](https://cloud.githubusercontent.com/assets/140742/23743362/9a62dc1a-04b0-11e7-880b-b71dff20d8cf.jpg)

**Comment by isholgueras** [comment]
LOL, The PR was there xD. I'm sick. This flu will kill me soon.

One thing, I fix somethings of the picture. 

- The picture wasn't horizontal, so I rotated a bit to correct it.
- The picture in raw was too bright, so I added a blue layer, similar than the previous, to dim it a bit.

**Comment by juampynr** [comment]
Fixed and merged. Thanks @isholgueras!
