### ISSUE TITLE
Call 4 Papers

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#95]
We first need to choose between Google Forms or Trello.

Trello is simple and has an API. Google forms is more complex but also flexible. If Google Forms accepts an image field (very likely), then great, since that gives us a chance to use it as the speaker's headshot and pull all the data from the Google Forms API.

**Comment by nuez** [comment]
I don't think google forms accepts a file field, you can add images but as part of the form. As a trello aficcionado i prefer that one:)

**Comment by nuez** [comment]
the article that you created currently has the default styling of a page . see #96

**Comment by juampynr** [comment]
@samuelsolis @nuez we should adjust the current call for papers so it says that we will open it this week:

![image](https://cloud.githubusercontent.com/assets/108130/23890757/75128ff0-0893-11e7-9770-ec36e29bf2fc.png)

This is so we can publish the new version between today and tomorrow.

**Comment by samuelsolis** [comment]
Yes, I will adjust the Google form, but we already can create the link:

https://docs.google.com/forms/d/e/1FAIpQLSeRE_ix2e4fH4dNGSfupq5SqNRMtenv7fpu8sCHqAIo8J_Vng/viewform

I think that April, 10 is a good deadline to set in the block.

**Comment by samuelsolis** [comment]
I have change the Form link (now is shorter): https://goo.gl/forms/enN2RtAVE9YraljJ2

**Comment by juampynr** [comment]
https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/107
